Fix/teleport movement check
cervinakuy/KitPvP pull request #201
Opened 2022-02-27 22:10 UTC by makindotcc

2022-02-27 22:12 UTC, makindotcc commented
I wanted to create a pull request in our fork 💀

2022-02-27 22:26 UTC, makindotcc commented
okay, now i think it is ready to pr yours repo

2022-02-27 22:29 UTC, makindotcc commented
This glitch looks like this:
![image](https://user-images.githubusercontent.com/9150636/155902589-5e36602c-8698-484b-a6b6-30e32e99ab4f.png)

and mine patch should this fix this

2022-09-07 02:55 UTC, cervinakuy requested changes
Some changes (commented A, B, C) appear irrelevant to your overarching goal with the PR (fixing death animation desync). Please create one PR per requested change.
Additionally, while I recognize I don't have any code style guidelines at this time, [e0bdd05](https://github.com/Matt4499/KitPvP/commit/e0bdd05c3bbf7b43226eea080af1245857dc398b) seems like it reformats the entire project code.
Please address these changes at some point in the next weeks, otherwise I will close this

2022-09-07 02:55 UTC, cervinakuy commented on src/main/java/com/planetgallium/kitpvp/command/MainCommand.java
> -
Is this even relevant to fixing the death animation?

2022-09-07 02:55 UTC, cervinakuy commented on src/main/java/com/planetgallium/kitpvp/Game.java
> +		getCommand("kitpvp").setExecutor(mainCommand);
C

2022-09-07 02:55 UTC, cervinakuy commented on pom.xml
> +            <version>7.0.6</version>
B

2022-09-07 02:55 UTC, cervinakuy commented on pom.xml
>                          </configuration>
A

2022-09-07 21:40 UTC, makindotcc commented
I don't think I can do any changes anymore, because I'm not working at "kwadratowa" and I don't have access to this repo. In this PR there should be only this commit: [1ec7474](https://github.com/cervinakuy/KitPvP/pull/201/commits/1ec74744d0e424bce029b65f31da6ac20b5cdaa0), but I accidentally created a PR to your repo instead our.

2022-09-07 21:42 UTC, makindotcc commented
I'm closing it, because probably I cannot change it anymore.

2022-09-07 21:42 UTC, closed without merging